/*
 *
 * APRSWelcomeCenter
 * Copyright (c) 2026 John Rokicki KC1VMZ
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see
 * https://www.gnu.org/licenses/.
 *
 * http://www.kc1vmz.com
 */
package com.kc1vmz.aprswc.startup;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.kc1vmz.aprswc.accessor.CommunicationCategoryAccessor;
import com.kc1vmz.aprswc.object.CommunicationCategory;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.test.util.ReflectionTestUtils;
import reactor.core.publisher.Mono;

class CommunicationCategoryInitializerTest {
    @Test
    void createsAllDefaultCategoriesWithFixedIds() {
        CommunicationCategoryAccessor accessor = mock(CommunicationCategoryAccessor.class);
        when(accessor.createIfAbsent(any(CommunicationCategory.class)))
                .thenAnswer(invocation -> Mono.just(invocation.getArgument(0)));
        CommunicationCategoryInitializer initializer = new CommunicationCategoryInitializer();
        ReflectionTestUtils.setField(initializer, "accessor", accessor);

        initializer.run(mock(ApplicationArguments.class));

        ArgumentCaptor<CommunicationCategory> captor = ArgumentCaptor.forClass(CommunicationCategory.class);
        verify(accessor, org.mockito.Mockito.times(7)).createIfAbsent(captor.capture());
        List<CommunicationCategory> categories = captor.getAllValues();
        assertEquals(
                List.of("Welcome", "Goodbye", "Weather", "Commercial Radio", "Events", "Clubs", "Amateur Radio"),
                categories.stream().map(CommunicationCategory::getName).toList());
        assertTrue(categories.stream().allMatch(category -> category.getId() != null));
        assertTrue(categories.stream().allMatch(CommunicationCategory::isSystemDefined));
        assertTrue(categories.stream()
                .filter(category -> category.getName().equals("Weather"))
                .allMatch(CommunicationCategory::isAutoGeneratedText));
        assertTrue(categories.stream()
                .filter(category -> !category.getName().equals("Weather"))
                .allMatch(category -> !category.isAutoGeneratedText()));
        assertFalse(categories.isEmpty());
    }
}
