spring.main.banner-mode=off
spring.application.name=APRSWC
spring.datasource.url=jdbc:h2:file:${APRSWC_DB_DIR:./data}/aprswc;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.web.resources.cache.cachecontrol.no-store=true
aprswc.application-version.application-name=APRSWelcomeCenter
aprswc.application-version.version=1.0.4
aprswc.application-version.author=John Rokicki KC1VMZ
aprswc.application-version.copyright-year=2026
aprswc.application-version.website=http://www.kc1vmz.com

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
