/*
 *
 * APRSWelcomeCenter
 * Copyright (c) 2026 John Rokicki KC1VMZ
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see
 * https://www.gnu.org/licenses/.
 *
 * http://www.kc1vmz.com
 */
package com.kc1vmz.aprswc.object;

import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(
        name = "communication_categories",
        uniqueConstraints = @UniqueConstraint(name = "uk_category_name", columnNames = "name"))
public class CommunicationCategory {
    @Id
    private UUID id;

    @Column(nullable = false)
    private String name;

    @Column(length = 4000)
    private String description;

    private boolean autoGeneratedText;

    private boolean systemDefined;

    /** Required only by JPA. */
    protected CommunicationCategory() {}

    public CommunicationCategory(
            UUID id, String name, String description, boolean autoGeneratedText, boolean systemDefined) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.autoGeneratedText = autoGeneratedText;
        this.systemDefined = systemDefined;
    }

    @PrePersist
    void assignId() {
        if (id == null) id = UUID.randomUUID();
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID v) {
        id = v;
    }

    public String getName() {
        return name;
    }

    public void setName(String v) {
        name = v;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String v) {
        description = v;
    }

    public boolean isAutoGeneratedText() {
        return autoGeneratedText;
    }

    public void setAutoGeneratedText(boolean value) {
        autoGeneratedText = value;
    }

    public boolean isSystemDefined() {
        return systemDefined;
    }

    public void setSystemDefined(boolean value) {
        systemDefined = value;
    }
}
