/*
 *
 * APRSWelcomeCenter
 * Copyright (c) 2026 John Rokicki KC1VMZ
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see
 * https://www.gnu.org/licenses/.
 *
 * http://www.kc1vmz.com
 */
package com.kc1vmz.aprswc.content;

import com.kc1vmz.aprswc.enumeration.PolicyContentSource;
import com.kc1vmz.aprswc.object.CommunicationPolicy;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public class PolicyContentService {
    private static final Logger LOG = LoggerFactory.getLogger(PolicyContentService.class);
    private final TinyTopicsClient client;
    private final JdbcTemplate jdbc;
    private final ConcurrentHashMap<Key, CompletableFuture<String>> pending;

    public PolicyContentService(TinyTopicsClient client, JdbcTemplate jdbc) {
        this.client = client;
        this.jdbc = jdbc;
        this.pending = new ConcurrentHashMap<>();
    }

    public static void validate(CommunicationPolicy policy) {
        if (policy.getContentSource() == null) throw invalid("Content source is required");
        if (policy.getCategory().isAutoGeneratedText()) {
            policy.setContentSource(PolicyContentSource.TEXT);
            policy.setTopicId(null);
            policy.setTopicParameters(Map.of());
            return;
        }
        if (policy.getContentSource() == PolicyContentSource.TINYTOPICS
                && (policy.getTopicId() == null || !policy.getTopicId().matches("[a-z0-9-]{1,40}")))
            throw invalid("Choose a TinyTopics topic");
        if (policy.getTopicId() != null && !policy.getTopicId().matches("[a-z0-9-]{1,40}"))
            throw invalid("Invalid TinyTopics topic ID");
        if (policy.getTopicParameters() == null || policy.getTopicParameters().size() > 100)
            throw invalid("Invalid TinyTopics parameters");
        policy.getTopicParameters().forEach((name, value) -> {
            if (name == null
                    || name.isBlank()
                    || name.length() > 255
                    || name.equals("length")
                    || name.equals("format")
                    || value == null
                    || value.length() > 4000) throw invalid("Invalid TinyTopics parameter");
        });
    }

    private static ResponseStatusException invalid(String message) {
        return new ResponseStatusException(HttpStatus.BAD_REQUEST, message);
    }

    public String resolve(CommunicationPolicy policy) {
        return resolve(policy, "E:" + UUID.randomUUID());
    }

    public String resolve(CommunicationPolicy policy, String occurrence) {
        if (policy.getContentSource() != PolicyContentSource.TINYTOPICS
                || (policy.getCategory() != null && policy.getCategory().isAutoGeneratedText()))
            return policy.getMessageText();
        Key key = new Key(policy.getId(), policy.getVersion(), occurrence);
        CompletableFuture<String> result = new CompletableFuture<>();
        var existing = pending.putIfAbsent(key, result);
        if (existing != null) return existing.join();
        try {
            var saved = jdbc.queryForList(
                    "select resolved_text from policy_content_results where policy_id=? and policy_version=? and occurrence_key=?",
                    String.class,
                    key.policy(),
                    key.version(),
                    key.occurrence());
            if (!saved.isEmpty()) {
                result.complete(saved.getFirst());
                return saved.getFirst();
            }
            var resolved = client.resolve(policy.getTopicId(), policy.getTopicParameters());
            if (resolved.error() != null)
                LOG.warn("Policy {} topic {}: {}", policy.getId(), policy.getTopicId(), resolved.error());
            jdbc.update(
                    "insert into policy_content_results(policy_id,policy_version,occurrence_key,topic_id,requested_at,content_status,http_status,error_message,resolved_text) select ?,?,?,?,?,?,?,?,? where exists(select 1 from communication_policies where id=?)",
                    key.policy(),
                    key.version(),
                    key.occurrence(),
                    policy.getTopicId(),
                    Timestamp.from(Instant.now()),
                    resolved.status(),
                    resolved.httpStatus(),
                    limited(resolved.error()),
                    resolved.text(),
                    key.policy());
            result.complete(resolved.text());
            return resolved.text();
        } catch (RuntimeException error) {
            result.completeExceptionally(error);
            throw error;
        } finally {
            pending.remove(key, result);
        }
    }

    public List<Map<String, Object>> history(UUID policy) {
        return jdbc.queryForList(
                "select occurrence_key,topic_id,requested_at,content_status,http_status,error_message,resolved_text from policy_content_results where policy_id=? order by requested_at desc fetch first 50 rows only",
                policy);
    }

    private String limited(String value) {
        return value == null ? null : value.substring(0, Math.min(4000, value.length()));
    }

    private record Key(UUID policy, long version, String occurrence) {}
}
