EXECUTE IMMEDIATE 'ALTER TABLE COMMUNICATION_INSTANCES DROP CONSTRAINT ' || QUOTE_IDENT(
    (SELECT tc.CONSTRAINT_NAME 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
     JOIN INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc 
       ON tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
     WHERE tc.TABLE_NAME = 'COMMUNICATION_INSTANCES' 
       AND tc.CONSTRAINT_TYPE = 'CHECK'
       AND cc.CHECK_CLAUSE LIKE '%TYPE%' 
       AND cc.CHECK_CLAUSE LIKE '%APRS_IS%'
     LIMIT 1)
);

-- Re-create with the name explicitly defined
ALTER TABLE COMMUNICATION_INSTANCES 
ADD CONSTRAINT CK_COMMUNICATION_INSTANCES_TYPE 
CHECK (TYPE IN ('APRS_IS', 'KISS_TCP', 'KISS_SERIAL', 'TNC2_SERIAL', 'TNC2_TCP'));
