ALTER TABLE communication_instances DROP CONSTRAINT CK_COMMUNICATION_INSTANCES_TYPE;
ALTER TABLE communication_instances ADD CONSTRAINT CK_COMMUNICATION_INSTANCES_TYPE
    CHECK (type IN ('APRS_IS','KISS_TCP','KISS_SERIAL','TNC2_TCP','TNC2_SERIAL','KENWOOD_SERIAL'));
ALTER TABLE communication_instances ADD COLUMN transmit_enabled BOOLEAN DEFAULT TRUE NOT NULL;
