/*
 *
 * APRSWelcomeCenter
 * Copyright (c) 2026 John Rokicki KC1VMZ
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see
 * https://www.gnu.org/licenses/.
 *
 * http://www.kc1vmz.com
 */
package com.kc1vmz.aprswc.database;

import static org.junit.jupiter.api.Assertions.assertTrue;

import com.kc1vmz.aprswc.object.CommunicationCategory;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

@DataJpaTest
class CommunicationCategoryRepositoryTest {
    @Autowired
    private CommunicationCategoryRepository repository;

    @Autowired
    private TestEntityManager entityManager;

    @Test
    void persistsCategoryFlags() {
        CommunicationCategory saved =
                repository.saveAndFlush(new CommunicationCategory(null, "Weather", "Weather text", true, true));

        entityManager.clear();
        CommunicationCategory found = repository.findById(saved.getId()).orElseThrow();

        assertTrue(found.isAutoGeneratedText());
        assertTrue(found.isSystemDefined());
    }
}
