const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../../main/resources/static/policy-content.js'), 'utf8');

function setup(fetchTopics = async () => [{id: 'weather', description: 'Weather', parameterNames: ['x', 'y']}]) {
    const node = tag => ({tag, value: '', textContent: '', children: [], dataset: {}, listeners: {},
        addEventListener(event, fn) {this.listeners[event] = fn;},
        setAttribute(key, value) {this[key] = value;},
        append(child) {this.children.push(child);},
        replaceChildren() {this.children = [];},
        querySelectorAll(tag) {return this.children.flatMap(child => child.tag === tag ? [child] : child.querySelectorAll(tag));}
    });
    const fields = {categoryId: {value: 'general'}, communicationEventType: {value: 'SCHEDULED_ONCE'}, messageText: {value: 'Original text'}};
    const buttons = ['TEXT', 'TINYTOPICS'].map(value => {const b = node('button'); b.dataset.policyContent = value; return b;});
    const nodes = Object.fromEntries(['policy-topic', 'policy-topic-parameters', 'policy-topic-message', 'policy-content-history', 'policy-text-field', 'policy-topic-fields'].map(id => ['#' + id, node('div')]));
    nodes['#policy-form'] = {elements: fields};
    const categories = new Map([['general', {autoGeneratedText: false}], ['auto', {autoGeneratedText: true}]]);
    const context = vm.createContext({window: {}, communicationCategories: categories, document: {
        querySelector: selector => nodes[selector], querySelectorAll: () => buttons, createElement: node
    }, fetch: async url => ({ok: true, json: async () => url.includes('content-results') ? [] : fetchTopics()})});
    vm.runInContext(source, context);
    return {api: context.window.policyContent, nodes, fields, buttons};
}

test('switches sources and preserves text and parameter drafts', async () => {
    const ui = setup();
    await ui.api.load(null);
    ui.buttons[1].listeners.click();
    assert.equal(ui.fields.messageText.required, false);
    assert.equal(ui.fields.messageText.disabled, true);
    ui.nodes['#policy-topic'].value = 'weather';
    ui.nodes['#policy-topic'].listeners.change();
    const inputs = ui.nodes['#policy-topic-parameters'].querySelectorAll('input');
    inputs[0].value = '-72.97'; inputs[0].listeners.input();
    ui.buttons[0].listeners.click();
    assert.equal(ui.fields.messageText.value, 'Original text');
    assert.equal(ui.fields.messageText.required, true);
    ui.buttons[1].listeners.click();
    assert.deepEqual(JSON.parse(JSON.stringify(ui.api.value())), {contentSource: 'TINYTOPICS', topicId: 'weather', topicParameters: {x: '-72.97', y: ''}});
});

test('unavailable server disables topic selector and preserves saved configuration', async () => {
    const ui = setup(async () => {throw new Error('offline');});
    await ui.api.load({id: 'policy', contentSource: 'TINYTOPICS', topicId: 'weather', topicParameters: {x: '-72'}});
    assert.equal(ui.nodes['#policy-topic'].disabled, true);
    assert.equal(ui.nodes['#policy-topic'].children[0].textContent, 'No topics available');
    assert.equal(ui.api.value().topicId, 'weather');
    assert.equal(ui.api.value().topicParameters.x, '-72');
});

test('generated categories disable content controls without requiring text', async () => {
    const ui = setup();
    await ui.api.load({contentSource: 'TINYTOPICS', topicId: 'weather', topicParameters: {}});
    ui.fields.categoryId.value = 'auto'; ui.api.update();
    assert.ok(ui.buttons.every(button => button.disabled));
    assert.equal(ui.fields.messageText.disabled, true);
    assert.equal(ui.fields.messageText.required, false);
    assert.equal(ui.nodes['#policy-topic-fields'].hidden, true);
    assert.equal(ui.api.value().contentSource, 'TEXT');
});

test('a late topic response cannot overwrite a newly opened policy', async () => {
    let release;
    const delayed = new Promise(resolve => {release = resolve;});
    let calls = 0;
    const ui = setup(() => ++calls === 1 ? delayed : []);
    const first = ui.api.load({contentSource: 'TINYTOPICS', topicId: 'first', topicParameters: {}});
    await ui.api.load({contentSource: 'TINYTOPICS', topicId: 'second', topicParameters: {}});
    release([{id: 'first', parameterNames: []}]); await first;
    assert.equal(ui.api.value().topicId, 'second');
    assert.equal(ui.nodes['#policy-topic'].disabled, true);
});
